[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Label(id='label1')
PushConstantV(value=2)
GlobalLoad16(nargs=1, popoffset=True, address=8)
PushConstantV(value=1)
GlobalLoad16(nargs=1, popoffset=True, address=8)
PushConstantV(value=0)
GlobalLoad16(nargs=1, popoffset=True, address=8)
PushConstantV(value=2)
GlobalLoadS8(nargs=1, popoffset=True, address=5)
PushConstantV(value=1)
GlobalLoadS8(nargs=1, popoffset=True, address=5)
PushConstantV(value=0)
GlobalLoadS8(nargs=1, popoffset=True, address=5)
PushConstantV(value=2)
GlobalLoadU8(nargs=1, popoffset=True, address=2)
PushConstantV(value=1)
GlobalLoadU8(nargs=1, popoffset=True, address=2)
PushConstantV(value=0)
GlobalLoadU8(nargs=1, popoffset=True, address=2)
GlobalLoad16(nargs=1, popoffset=False, address=0)
PushConstantV(value=10)
CallUserFunction(funcid=1)
DropValue()
Return0()
PushZeros(n=3)
CallV(address=LabelRef('label1'))
DropValue()
PushConstantV(value=2)
PopLocal(sfa=0)
PushConstantV(value=5)
PopLocal(sfa=1)
PushConstantV(value=8)
PopLocal(sfa=2)
PushConstantV(value=65)
PushConstantV(value=0)
GlobalStoreU8(nargs=1, popoffset=True, address=2)
PushConstantV(value=100)
PushConstantV(value=2)
GlobalStoreU8(nargs=1, popoffset=True, address=2)
PushLocal(sfa=0)
PushConstantV(value=0)
Add()
GlobalLoadU8(nargs=0, popoffset=True, address=None)
PushConstantV(value=0)
GlobalStoreS8(nargs=1, popoffset=True, address=5)
PushLocal(sfa=0)
PushConstantV(value=2)
Add()
GlobalLoadU8(nargs=0, popoffset=True, address=None)
PushConstantV(value=2)
GlobalStoreS8(nargs=1, popoffset=True, address=5)
PushLocal(sfa=0)
GlobalLoadU8(nargs=0, popoffset=True, address=None)
PushConstantV(value=0)
GlobalStore16(nargs=1, popoffset=True, address=8)
PushLocal(sfa=0)
PushConstantV(value=2)
Add()
GlobalLoadU8(nargs=0, popoffset=True, address=None)
PushConstantV(value=2)
GlobalStore16(nargs=1, popoffset=True, address=8)
PushLocal(sfa=0)
Bury(k=0)
GlobalLoadU8(nargs=0, popoffset=True, address=None)
PushConstantV(value=1)
Add()
Dig(k=0)
GlobalStoreU8(nargs=0, popoffset=True, address=None)
PushConstantV(value=8)
PushLocal(sfa=0)
PushConstantV(value=1)
Add()
GlobalStoreU8(nargs=0, popoffset=True, address=None)
PushLocal(sfa=0)
PushConstantV(value=2)
Add()
Bury(k=0)
GlobalLoadU8(nargs=0, popoffset=True, address=None)
PushConstantV(value=1)
Sub()
Dig(k=0)
GlobalStoreU8(nargs=0, popoffset=True, address=None)
PushLocal(sfa=1)
Bury(k=0)
GlobalLoadU8(nargs=0, popoffset=True, address=None)
PushConstantV(value=1)
Add()
Dig(k=0)
GlobalStoreU8(nargs=0, popoffset=True, address=None)
PushConstantV(value=-8)
PushLocal(sfa=1)
PushConstantV(value=1)
Add()
GlobalStoreU8(nargs=0, popoffset=True, address=None)
PushLocal(sfa=1)
PushConstantV(value=2)
Add()
Bury(k=0)
GlobalLoadU8(nargs=0, popoffset=True, address=None)
PushConstantV(value=1)
Sub()
Dig(k=0)
GlobalStoreU8(nargs=0, popoffset=True, address=None)
PushLocal(sfa=2)
Bury(k=0)
GlobalLoad16(nargs=0, popoffset=True, address=None)
PushConstantV(value=1)
Add()
Dig(k=0)
GlobalStore16(nargs=0, popoffset=True, address=None)
PushConstantV(value=1616)
PushLocal(sfa=2)
PushConstantV(value=1)
PushConstantV(value=1)
ShiftLeft()
Add()
GlobalStore16(nargs=0, popoffset=True, address=None)
PushLocal(sfa=2)
PushConstantV(value=2)
PushConstantV(value=1)
ShiftLeft()
Add()
Bury(k=0)
GlobalLoad16(nargs=0, popoffset=True, address=None)
PushConstantV(value=1)
Sub()
Dig(k=0)
GlobalStore16(nargs=0, popoffset=True, address=None)
PushConstantV(value=0)
PopLocal(sfa=0)
PushLocal(sfa=0)
Bury(k=0)
GlobalLoad16(nargs=0, popoffset=True, address=None)
PushConstantV(value=8)
Add()
Dig(k=0)
GlobalStore16(nargs=0, popoffset=True, address=None)
CallV(address=LabelRef('label1'))
DropValue()
StackFramePointer()
PushConstantV(value=4)
Sub()
PopLocal(sfa=0)
PushLocal(sfa=2)
PushConstantV(value=2)
Add()
PushLocal(sfa=0)
GlobalStore16(nargs=0, popoffset=True, address=None)
PushLocal(sfa=1)
Bury(k=0)
GlobalLoad16(nargs=0, popoffset=True, address=None)
PushConstantV(value=1000)
Sub()
Dig(k=0)
GlobalStore16(nargs=0, popoffset=True, address=None)
PushLocal(sfa=1)
Bury(k=0)
GlobalLoad16(nargs=0, popoffset=True, address=None)
PushConstantV(value=-1)
Mul()
Dig(k=0)
GlobalStore16(nargs=0, popoffset=True, address=None)
PushConstantV(value=0)
Bury(k=0)
GlobalLoad16(nargs=0, popoffset=True, address=None)
PushConstantV(value=3)
Sub()
Dig(k=0)
GlobalStore16(nargs=0, popoffset=True, address=None)
PushConstantV(value=14)
PopLocal(sfa=3)
PushLocal(sfa=3)
CallAddress()
DropValue()
Return0()